name: signature_pad_widget
description: Flutter widget for allowing the user to sign their name
version: 2.0.0
homepage: https://github.com/MisterJimson/signature-pad-dart

dependencies:
  stream_transform: ^1.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.8.0+1

environment:
  sdk: '>=2.3.0 <3.0.0'

flutter: